// Generated by CIRCT firtool-1.139.0
module VecAdd2(
  input        clock,
               reset,
  input  [1:0] io_vecA_0,
               io_vecA_1,
               io_vecA_2,
               io_vecA_3,
               io_vecA_4,
               io_vecA_5,
               io_vecA_6,
               io_vecA_7,
               io_vecA_8,
               io_vecA_9,
               io_vecA_10,
               io_vecA_11,
               io_vecA_12,
               io_vecA_13,
               io_vecA_14,
               io_vecA_15,
               io_vecA_16,
               io_vecA_17,
               io_vecA_18,
               io_vecA_19,
               io_vecA_20,
               io_vecA_21,
               io_vecA_22,
               io_vecA_23,
               io_vecA_24,
               io_vecA_25,
               io_vecA_26,
               io_vecA_27,
               io_vecA_28,
               io_vecA_29,
               io_vecA_30,
               io_vecA_31,
               io_vecB_0,
               io_vecB_1,
               io_vecB_2,
               io_vecB_3,
               io_vecB_4,
               io_vecB_5,
               io_vecB_6,
               io_vecB_7,
               io_vecB_8,
               io_vecB_9,
               io_vecB_10,
               io_vecB_11,
               io_vecB_12,
               io_vecB_13,
               io_vecB_14,
               io_vecB_15,
               io_vecB_16,
               io_vecB_17,
               io_vecB_18,
               io_vecB_19,
               io_vecB_20,
               io_vecB_21,
               io_vecB_22,
               io_vecB_23,
               io_vecB_24,
               io_vecB_25,
               io_vecB_26,
               io_vecB_27,
               io_vecB_28,
               io_vecB_29,
               io_vecB_30,
               io_vecB_31,
  output [2:0] io_vecSum_0,
               io_vecSum_1,
               io_vecSum_2,
               io_vecSum_3,
               io_vecSum_4,
               io_vecSum_5,
               io_vecSum_6,
               io_vecSum_7,
               io_vecSum_8,
               io_vecSum_9,
               io_vecSum_10,
               io_vecSum_11,
               io_vecSum_12,
               io_vecSum_13,
               io_vecSum_14,
               io_vecSum_15,
               io_vecSum_16,
               io_vecSum_17,
               io_vecSum_18,
               io_vecSum_19,
               io_vecSum_20,
               io_vecSum_21,
               io_vecSum_22,
               io_vecSum_23,
               io_vecSum_24,
               io_vecSum_25,
               io_vecSum_26,
               io_vecSum_27,
               io_vecSum_28,
               io_vecSum_29,
               io_vecSum_30,
               io_vecSum_31
);

  assign io_vecSum_0 = {1'h0, io_vecA_0 + io_vecB_0};
  assign io_vecSum_1 = {1'h0, io_vecA_1 + io_vecB_1};
  assign io_vecSum_2 = {1'h0, io_vecA_2 + io_vecB_2};
  assign io_vecSum_3 = {1'h0, io_vecA_3 + io_vecB_3};
  assign io_vecSum_4 = {1'h0, io_vecA_4 + io_vecB_4};
  assign io_vecSum_5 = {1'h0, io_vecA_5 + io_vecB_5};
  assign io_vecSum_6 = {1'h0, io_vecA_6 + io_vecB_6};
  assign io_vecSum_7 = {1'h0, io_vecA_7 + io_vecB_7};
  assign io_vecSum_8 = {1'h0, io_vecA_8 + io_vecB_8};
  assign io_vecSum_9 = {1'h0, io_vecA_9 + io_vecB_9};
  assign io_vecSum_10 = {1'h0, io_vecA_10 + io_vecB_10};
  assign io_vecSum_11 = {1'h0, io_vecA_11 + io_vecB_11};
  assign io_vecSum_12 = {1'h0, io_vecA_12 + io_vecB_12};
  assign io_vecSum_13 = {1'h0, io_vecA_13 + io_vecB_13};
  assign io_vecSum_14 = {1'h0, io_vecA_14 + io_vecB_14};
  assign io_vecSum_15 = {1'h0, io_vecA_15 + io_vecB_15};
  assign io_vecSum_16 = {1'h0, io_vecA_16 + io_vecB_16};
  assign io_vecSum_17 = {1'h0, io_vecA_17 + io_vecB_17};
  assign io_vecSum_18 = {1'h0, io_vecA_18 + io_vecB_18};
  assign io_vecSum_19 = {1'h0, io_vecA_19 + io_vecB_19};
  assign io_vecSum_20 = {1'h0, io_vecA_20 + io_vecB_20};
  assign io_vecSum_21 = {1'h0, io_vecA_21 + io_vecB_21};
  assign io_vecSum_22 = {1'h0, io_vecA_22 + io_vecB_22};
  assign io_vecSum_23 = {1'h0, io_vecA_23 + io_vecB_23};
  assign io_vecSum_24 = {1'h0, io_vecA_24 + io_vecB_24};
  assign io_vecSum_25 = {1'h0, io_vecA_25 + io_vecB_25};
  assign io_vecSum_26 = {1'h0, io_vecA_26 + io_vecB_26};
  assign io_vecSum_27 = {1'h0, io_vecA_27 + io_vecB_27};
  assign io_vecSum_28 = {1'h0, io_vecA_28 + io_vecB_28};
  assign io_vecSum_29 = {1'h0, io_vecA_29 + io_vecB_29};
  assign io_vecSum_30 = {1'h0, io_vecA_30 + io_vecB_30};
  assign io_vecSum_31 = {1'h0, io_vecA_31 + io_vecB_31};
endmodule

